seed_apps = [
#    'com.eco.note',
#    'com.swiftnotes.android',
#    'com.benoitletondor.easybudgetapp',
#    'luankevinferreira.expenses',
#    'com.kvannli.simonkvannli.dailybudget',
#    'com.blogspot.e_kanivets.moneytracker',
#    'pl.com.andrzejgrzyb.shoppinglist',
#    'br.com.activity',
#    'privacyfriendlyshoppinglist.secuso.org.privacyfriendlyshoppinglist',
#    'org.openintents.shopping',
'com.boedec.hoel.speaker.cleaner.remove.water',
'com.samidbangkit.freevpn',
'androing.linuxhandbook',
'com.bickster.walkbeforeyourun',
'co.easyroads.app',
'com.snscorp.tea_recipes',
'com.sofachairdesign.atharizu',
'com.cookware.eggrecipes',
'com.bigsilentmonkey.testedadmentalconcolores'
]

database_path = './output/database-research-server.db'
preprocessed_data_path = './output/preprocessed.csv'
model_path = './output/word2vec.model'
